services:
  # --- existing infra ---
  mongo:
    image: mongo:6
    ports: ["27017:27017"]

  # --- new Auth container ---
  auth:
    build: ./services/auth
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/auth_db
      - JWT_SECRET=mySuperSecret            # or ${JWT_SECRET} from .env
    depends_on:
      - mongo
    ports:
      - "3001:3000"        # host 3001 → container 3000

  ride:
    build: ./services/ride
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/ride_db
      # ⬇︎  Add this line if it’s missing
      - JWT_SECRET=mySuperSecret
    depends_on:
      - mongo
    ports:
      - "3002:3000"

