services:
  # --- existing infra ---
  mongo:
    image: mongo:6
    ports: ["27017:27017"]

  # --- new Auth container ---
  auth:
    build: ./services/auth
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/auth_db
      - JWT_SECRET=mySuperSecret            # or ${JWT_SECRET} from .env
    depends_on:
      - mongo
    ports:
      - "3001:3000"        # host 3001 → container 3000

  ride:
    build: ./services/ride
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/ride_db
      # ⬇︎  Add this line if it’s missing
      - JWT_SECRET=mySuperSecret
    depends_on:
      - mongo
    ports:
      - "3002:3000"

  trip:
    build: ./services/trip
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/trip_db
      - JWT_SECRET=mySuperSecret       # must match Auth & Ride
    depends_on:
      - mongo
    ports:
      - "3003:3000"

  gateway:
    build: ./gateway
    ports:
      - "8080:80"          # host 8080 → container 80
    depends_on:
      - auth
      - ride
      - trip  
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]   # 15672 = web UI

    

